Adding known issue for igGridGroupBy with Remote Paging
IgniteUI/help-topics pull request #120
Opened 2017-01-10 12:53 UTC by MayaKirova

Related to bug 228332.

2017-01-10 14:09 UTC, mpavlinov requested changes

2017-01-10 14:09 UTC, mpavlinov commented on topics/02_Controls/igGrid/09_igGrid_Known_Issues.md
> +Remote GroupBy does not work as expected with Remote Paging. | When remote paging and remote groupBy are enabled the page count and page size are incorrect.| ![](../../images/images/negative.png)
"When remote paging and remote groupBy" => "When remote Paging and remote GroupBy". The name of the features should be capitalized.

2017-01-10 14:09 UTC, mpavlinov commented on topics/08_Known-Issues/01_Known_Issues_and_Limitations_2016_Volume_2.md
> +Remote GroupBy does not work as expected with Remote Paging. | When remote paging and remote groupBy are enabled the page count and page size are incorrect.| ![](../images/images/negative.png)
"When remote paging and remote groupBy" => "When remote Paging and remote GroupBy". The name of the features should be capitalized.

2017-01-10 14:15 UTC, mpavlinov approved these changes

2017-01-10 14:15 UTC, merged

2017-01-12 17:30 UTC, ig-ealbert commented
@mpavlinov I commited the translation to 16.2 help-topics-ja.  This is no longer pending translation.