Revising virtualization configuration topic
IgniteUI/help-topics pull request #137
Opened 2017-02-16 16:28 UTC by MayaKirova

Related to bugs 232322 and 232674

2017-02-17 12:36 UTC, mpavlinov requested changes
1. Please add a separate section for column virtualization. If the developer is particularly interested to configure column virtualization he will search for such section.
2. Add a link to the "Feature Compatibility Matrix" in the "Related Topics" section.
3. Add new section "Enabling and Configuring Column Virtualization". Put it after the continuous virtualization section.
4. Remove "Enabling Virtualization Overview" section. It basically describes how to enable column virtualization.
5. In "Enabling and Configuring Fixed Virtualization" section talk about how to enable only fixed row virtualization. Remove any information about the column virtualization. Leave one note that links to column virtualization.
6.In "Enabling and Configuring Continuous Virtualization" section property settings are not correct and the example is not correct. Remove the "GetGlobalResourceObject" from the sample.

2017-02-21 08:02 UTC, kdinev commented
@MayaKirova make it more explicit that the virtualization feature is usable in very specific scenarios when you cannot turn on other paging features because of an application requirement, and the size of the data is mid-range (1000-10000 records).

2017-02-24 15:54 UTC, kdinev commented
@mpavlinov Would you approve with the latest changes, or does the topic require more changes?

2017-02-24 17:05 UTC, mpavlinov approved these changes

2017-02-24 17:05 UTC, mpavlinov commented
@kdinev: I made some changes to the topics. Please, review them.

2017-02-27 12:28 UTC, kdinev commented on topics/02_Controls/igGrid/03_Features/13_Virtualization/00_igGrid_Virtualization_Overview.md
> +Virtualization is a feature of the `igGrid` that boosts performance when displaying large data sets containing thousands of records. It improves both rendering time and scrolling as well as memory fo
The topic still doesn't state that this feature is not the feature of choice if you can enable, for example, paging. Also I didn't find anything related to the optimal number of records this feature is suitable for.

2017-02-27 12:31 UTC, kdinev commented
You can also add the information that virtualization is really optimal for a scenario with 1000-10000 records all displayed in one page.

2017-02-27 12:31 UTC, kdinev requested changes
I left a comment above.

2017-03-02 13:11 UTC, mpavlinov commented
@kdinev I applied your comments. Please, review.

2017-03-02 15:02 UTC, kdinev approved these changes

2017-03-09 09:58 UTC, merged