Adding topic "Localizing igEditors"
IgniteUI/help-topics pull request #139
Opened 2017-02-20 11:21 UTC by dafo

2017-02-20 14:11 UTC, dafo commented
This should not be merged as more information must be provided in the new topic.

2017-02-21 11:35 UTC, kdinev requested changes

2017-02-21 11:35 UTC, kdinev commented on topics/02_Controls/igEditors/Config/03_Localizing_igEditors.md
> +The regional settings, on the other hand, provide localized formats including dates, numbers, and currency symbols for the editors. These reside in the ../js/modules/i18n/regional (where js is the ro
provide region specific formats for dates, numbers, as well as currency symbols, floating point symbols, decimal separators, default decimal rounding, etc.

2017-02-21 11:35 UTC, kdinev commented on topics/02_Controls/igEditors/Config/03_Localizing_igEditors.md
> +In this sample we show how a culture can be set to the editors' `regional` option to change the format of dates, times, numbers and currencies. Three regions are configured here (United States, Japan
change the default formatting of dates, numbers, and currencies.

2017-02-24 15:47 UTC, kdinev approved these changes

2017-02-24 15:47 UTC, kdinev commented
@dafo Is this ready to merge?

2017-02-27 06:58 UTC, dafo commented
@kdinev I think it is ready to be merged.

2017-02-27 11:21 UTC, merged