Moving Knockout sample to igCombo knockoutjs support topic
IgniteUI/help-topics pull request #150
Opened 2017-02-21 12:38 UTC by zdrawku

2017-02-21 12:54 UTC, d-georgiev-91 approved these changes

2017-02-21 13:56 UTC, mpavlinov requested changes

2017-02-21 13:56 UTC, mpavlinov commented on topics/02_Controls/igCombo/04_Configuring/04_igCombo_KnockoutJS_Support.md
>  -	[Migrating to the New Combo](igCombo-Migrating-To-The-New-Combo.html#ko_changes): This topic aims to help with migration from old combo to the new one. The document includes the changes in the Knoc
This line should be in the "Topics" section

2017-02-22 13:53 UTC, mpavlinov approved these changes

2017-02-22 13:53 UTC, merged