Move Series Highlighting samples
IgniteUI/help-topics pull request #155
Opened 2017-02-21 14:33 UTC by Lipata

Move Series Highlighting, Series Highlighting (Financial) and Custom Series Highlighting samples to Configuring the Series Highlighting (igDataChart) topic.

2017-02-23 07:36 UTC, damyanpetev requested changes
@Lipata The updated image kind of lost the actual highlight demonstration in the process. Can we update it to something similar like the old one?

2017-02-23 13:50 UTC, Lipata commented
Here it is the new JP screenshto

![jquery_series_highlighting_01](https://cloud.githubusercontent.com/assets/2621802/23261625/d58917a4-f9df-11e6-8ebe-fe60d2da064f.png)

2017-02-24 12:08 UTC, damyanpetev commented
Tagging @ig-ealbert for the image :)

2017-02-24 12:42 UTC, damyanpetev approved these changes

2017-02-24 12:42 UTC, merged