write topic, move exporter samples to topics
IgniteUI/help-topics pull request #234
Opened 2017-03-02 12:01 UTC by hanastasov

Write topic for Configuring igGridExcelExporter
Move documentation samples to topics

2017-03-08 15:24 UTC, tiliev approved these changes

2017-03-08 17:00 UTC, mpavlinov requested changes
I edited all of the topics with my changes. However "Configuring igGridExcelExporter" still needs work.

2017-03-08 17:00 UTC, mpavlinov commented on topics/02_Controls/igGrid/11_igGridExcelExporter_Configuring.md
> +Configure Sorting | [sorting](%%jQueryApiUrl%%/ig.gridexcelexporter#options:settings.gridFeatureOptions.sorting) | Accepts values `"none"` or `"applied"`. When `"none"` Sorting is not applied in the
Please update the reference table for the options that you talk about in this section. Currently it's hard to keep track of what options you talk about and what are the possible values that the developer can set for them.

2017-03-08 17:00 UTC, mpavlinov commented on topics/02_Controls/igGrid/11_igGridExcelExporter_Configuring.md
> +Different options are available for configuring the `filtering`, `paging` and `hiding`. For example, we can opt to work with the visible `igGrid` columns only and do not export the hidden ones by set
You can put this information into the table above. Keep in mind that this topic is not to repeat the information from the API docs, but to add more value for the reader and actually describe actual end user scenarios. You can see how other "Configuration" topics are written. Most of them focus on user stories.

2017-03-08 17:00 UTC, mpavlinov commented on topics/02_Controls/igGrid/11_igGridExcelExporter_Configuring.md
> +The `igGridExcelExporter`™ provides options that allow any data and layout manipulations caused by the `igGrid` features to be reflected in the Excel Worksheet, as well as to configure styles to be a
Excel is a name of a product and always should be capitalized.

2017-03-08 17:00 UTC, mpavlinov commented on topics/02_Controls/igGrid/11_igGridExcelExporter_Configuring.md
> +All of these are enumerations and the `sorting`, `summaries` and `columnfixing` have only options - `"none"` or `"applied"`.
The option values that are strings should be enclosed in quotation marks.

2017-03-08 17:00 UTC, mpavlinov commented on topics/02_Controls/igGrid/11_igGridExcelExporter_Configuring.md
> +        showOverlay(args.grid, exportingOverlay);
As a reader I'm interested what is the definition of the `showOverlay` and `hideOverlay` functions. Please add their definitions to the code sample or better add a live sample.

2017-03-09 11:51 UTC, hanastasov commented on topics/02_Controls/igGrid/11_igGridExcelExporter_Configuring.md
> +        showOverlay(args.grid, exportingOverlay);
The content of `showOverlay` and `hideOverlay` is available in the live sample, which is in the end of document and I would prefer keeping the code sample more readable as it is now.

2017-03-09 15:33 UTC, hanastasov commented
Requested changes are introduced to the topic.

2017-03-09 23:14 UTC, mpavlinov approved these changes

2017-03-10 10:21 UTC, merged