fix: Updating the version of jQuery and jQuery UI
IgniteUI/help-topics pull request #354
Opened 2017-12-05 14:23 UTC by dafo

Closes #353

2017-12-05 14:43 UTC, kdinev requested changes

2017-12-05 14:43 UTC, kdinev commented on topics/01_General-and-Getting-Started/05_Deployment_Guide_Infragistics_Content_Delivery_Network(CDN).md
> +<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"type="text/javascript"></script>
Update directly to jQuery 3.2.1.

2017-12-06 06:44 UTC, kdinev approved these changes

2017-12-07 07:07 UTC, bazal4o approved these changes

2017-12-07 07:07 UTC, merged