Adding an Ignite UI CLI topic + Updating the existing topics with Ign…
IgniteUI/help-topics pull request #359
Opened 2018-01-09 12:14 UTC by dafo

…ite UI CLI information.

2018-01-10 14:56 UTC, bazal4o approved these changes

2018-01-10 15:04 UTC, kdinev requested changes

2018-01-10 15:04 UTC, kdinev commented on topics/home-page.md
> +<p>Get started by exploring the product documentation via the tree on this page or [run the samples](%%SamplesUrl%%/grid/overview), quickly create a new Angular, React ot jQuery application using the
or jQuery

2018-01-10 15:04 UTC, kdinev commented on topics/02_Controls/igEditors/05_igTextEditor/00_igTextEditor_Overview.md
> +For more information and the list of all available commands read [Using Ignite UI CLI](Using-Ignite-UI-CLI.html) topic.
read the ... topic.

2018-01-10 15:04 UTC, kdinev commented on topics/01_General-and-Getting-Started/17_Using_Ignite_UI_CLI.md
> +ig build
Doesn't `ig start` run `ig build`?

2018-01-10 15:04 UTC, kdinev commented on topics/01_General-and-Getting-Started/17_Using_Ignite_UI_CLI.md
> +Following are examples of how to use the `new` command to create an Ignite UI for JavaScript applications in all supported frameworks:<br/>
for all supported frameworks.

2018-01-10 15:04 UTC, kdinev commented on topics/01_General-and-Getting-Started/17_Using_Ignite_UI_CLI.md
> +The `build` command will install the npm packages that the project depends on. By default, it will install the [OSS version of Ignite UI](https://github.com/IgniteUI/ignite-ui) but it checks if a ful
Infragistics account credentials.

2018-01-10 15:52 UTC, bazal4o commented on topics/01_General-and-Getting-Started/17_Using_Ignite_UI_CLI.md
> +ig build
Yes but it still work both ways.

2018-01-10 20:31 UTC, bazal4o approved these changes

2018-01-11 09:49 UTC, kdinev approved these changes

2018-01-11 11:28 UTC, merged